### ISSUE TITLE
Doesn't seem to work with TwentyTwenty

### ISSUE THREAD

**Issue by ndegruchy** [janboddez/add-fediverse-icons-to-jetpack#1]
I've used this plugin for a bit, and with other themes, it works well. However, when using twentytwenty, it doesn't seem to set the icons correctly.

Is it due to TwentyTwenty using it's own setup?

**Comment by janboddez** [comment]
Fun thing is Twenty Twenty uses [nearly the exact same code](https://github.com/WordPress/WordPress/blob/001ffe81fbec4438a9f594f330e18103d21fbcd7/wp-content/themes/twentytwenty/inc/template-tags.php) to add its own (not Jetpack's) social menu icons. (The code that translates a URL to the correct domain is, at first glance, a bit different, though.)

Anyway, I think it's due to me checking for `jetpack-social-menu === $args->theme_location` and not, like Twenty Twenty, simply `social === $args->theme_location` in the nav menu element walker callback function.

So, I gave Twenty Twenty a spin, but I couldn't get it to show any social icons at all, even though I'd set my social links menu to the "social menu" location, and to the "footer menu" location, and ...

Otherwise I could at least have tried adding something like this, which should override above behavior, to my `functions.php`:
```
add_filter( 'walker_nav_menu_start_el', 'my_apply_icon', 100, 4 );
function my_apply_icon( $item_output, $item, $depth, $args ) {
	$social_icons = array(
		'Diaspora'   => 'diaspora',
		'Friendica'  => 'friendica',
		'GNU Social' => 'gnu-social',
		'Mastodon'   => 'mastodon',
		'PeerTube'   => 'peertube',
		'Pixelfed'   => 'pixelfed',
	);

	if ( 'social' === $args->theme_location ) {
		foreach ( $social_icons as $attr => $value ) {
			if ( false !== stripos( $item_output, $attr ) ) {
				$item_output = str_ireplace(
					$args->link_after,
					'</span>' . jetpack_social_menu_get_svg( array( 'icon' => esc_attr( $value ) ) ),
					$item_output
				);
			}
		}
	}

	return $item_output;
}
```

**Comment by janboddez** [comment]
So, yeah, probably its setup. If I ever figure out how to actually use Twenty Twenty, I'll gladly look into adding support for it.

**Comment by ndegruchy** [comment]
I did some research. Looks like, other than overriding the twentytwenty function for defining SVGs or [patching the social items class file](https://core.trac.wordpress.org/attachment/ticket/49034/class-twentytwenty-svg-icons.php.patch), [there is no way to easily to append to the social icons functionality](https://core.trac.wordpress.org/ticket/49034).

**Comment by ndegruchy** [comment]
> Fun thing is Twenty Twenty uses [nearly the exact same code](https://github.com/WordPress/WordPress/blob/001ffe81fbec4438a9f594f330e18103d21fbcd7/wp-content/themes/twentytwenty/inc/template-tags.php) to add its own (not Jetpack's) social menu icons. (The code that translates a URL to the correct domain is, at first glance, a bit different, though.)
> 
> Anyway, I think it's due to me checking for `jetpack-social-menu === $args->theme_location` and not, like Twenty Twenty, simply `social === $args->theme_location` in the nav menu element walker callback function.
> 
> So, I gave Twenty Twenty a spin, but I couldn't get it to show any social icons at all, even though I'd set my social links menu to the "social menu" location, and to the "footer menu" location, and ...
> 
> Otherwise I could at least have tried adding something like this, which should override above behavior, to my `functions.php`:
> 
> ```
> code
> ```

This works like a charm! With your plugin and a small amount of CSS to fix sizing, it works great!

```
.icon.icon-mastodon {
  height: 24px;
}
```
Thanks for your help!

**Comment by janboddez** [comment]
Cool! It seems, however, Twenty Twenty's "generic link" SVG is still being injected (which makes sense) into the HTML source ...

Below code is totally untested, but I think if you added a little regex to the snippet above, it would handle that. (Because of the high prio, our code runs after Twenty Twenty's, and we can remove the SVG already there.)
```
// Only for the Fediverse icons, remove whatever SVG's already there.
$item_output = preg_replace( '@<svg(.*?)</svg>@', '', $item_output );

// After that, inject our own.
$item_output = str_ireplace(
	$args->link_after,
	'</span>' . jetpack_social_menu_get_svg( array( 'icon' => esc_attr( $value ) ) ),
	$item_output
);
```

**Comment by ndegruchy** [comment]
Hmm, it seems it's a little greedy:
![1582147115](https://user-images.githubusercontent.com/52262673/74877492-8e0ee600-5333-11ea-9e13-f4d7331eed93.png)

**Comment by ndegruchy** [comment]
> Hmm, it seems it's a little greedy:
> ![1582147115](https://user-images.githubusercontent.com/52262673/74877492-8e0ee600-5333-11ea-9e13-f4d7331eed93.png)

Here's the full code:

```
add_filter( 'walker_nav_menu_start_el', 'my_apply_icon', 100, 4 );
function my_apply_icon( $item_output, $item, $depth, $args ) {
	$social_icons = array(
		'Diaspora'   => 'diaspora',
		'Friendica'  => 'friendica',
		'GNU Social' => 'gnu-social',
		'Mastodon'   => 'mastodon',
		'PeerTube'   => 'peertube',
		'Pixelfed'   => 'pixelfed',
	);

	if ( 'social' === $args->theme_location ) {
		foreach ( $social_icons as $attr => $value ) {
			if ( false !== stripos( $item_output, $attr ) ) {
				$item_output = str_ireplace(
					$args->link_after,
					'</span>' . jetpack_social_menu_get_svg( array( 'icon' => esc_attr( $value ) ) ),
					$item_output
				);
			}
		}
	}

    // Only for the Fediverse icons, remove whatever SVG's already there.
	$item_output = preg_replace( '@<svg(.*?)</svg>@', '', $item_output );

	// After that, inject our own.
	$item_output = str_ireplace(
		$args->link_after,
		'</span>' . jetpack_social_menu_get_svg( array( 'icon' => esc_attr( $value ) ) ),
		$item_output
	);

	return $item_output;
}
```

**Comment by janboddez** [comment]
Yeah, you would _replace_ the `$item_output = ...` inside the `if`
statement so that our regex and subsequent icon injection runs _only_ if
there's a match. I think right now you're pretty much overwriting all icons
with whatever happens to be the last array item (the final value of
`$value`).

**Comment by janboddez** [comment]
Yeah, you would actually just add the regex bit (the line with `preg_replace` in it) right before the string replacement, because that's what's happening, that was already inside the if statement.

Sorry if that wasn't sufficiently clear. I'd just give you the whole thing if I wasn't on my phone. Also, I wasn't 100% sure it'd work. :)

**Comment by ndegruchy** [comment]
That worked!

Thanks! I used to know how to do all of this, but I've long since lost the knack for it. Appreciate it.

**Comment by janboddez** [comment]
Awesome. Now, if you wanted to make things _even_ cleaner, you could also unhook the original (plugin) callback from `walker_nav_menu_start_el`. Except, uh, my plugin doesn't currently allow for that, which isn't very nice, I guess. (Created #3 for that, although it isn't an issue _per se_. Like, you wouldn't actually notice any difference.)

**Comment by janboddez** [comment]
Fixed that, and updated the snippet at—for now—https://github.com/janboddez/add-fediverse-icons-to-jetpack/blob/master/README.md#twenty-twenty-compatibility.

It's still kind of a hack—that code's almost as long as the main plugin file!—but it's the cleanest "solution" I can think of (and a bit beyond this tiny plugin's original scope, so yeah).
